In [1]:
import torch
import torch.nn as nn

class Model(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out


In [ ]:
features = torch.rand(10, 5)
model = Model(features.shape[1])
# we can also call model.forward(features) but this is recommended
print(f"Model Output: {model(features)}")
print(model.linear.weight, model.linear.bias)

Model Output: tensor([[0.4879],
        [0.4931],
        [0.4051],
        [0.4989],
        [0.4922],
        [0.3594],
        [0.5211],
        [0.4890],
        [0.4621],
        [0.4639]], grad_fn=<SigmoidBackward0>)
Parameter containing:
tensor([[-0.3356,  0.4238,  0.3176, -0.1611,  0.0063]], requires_grad=True) Parameter containing:
tensor([-0.1969], requires_grad=True)


In [7]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [8]:
"""
5 Nodes in Input Layer --> 3 Nodes in Hidden Layer --> 1 node in output Layer
"""

import torch
import torch.nn as nn


class Model(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features, 3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        return out

In [9]:
features = torch.rand(10, 5)
model = Model(features.shape[1])
# we can also call model.forward(features) but this is recommended
print(f"Model Output: {model(features)}")
print(model.linear1.weight, model.linear1.bias)
print(model.linear2.weight, model.linear2.bias)

Model Output: tensor([[0.3042],
        [0.3071],
        [0.2950],
        [0.3178],
        [0.2930],
        [0.3192],
        [0.2837],
        [0.3032],
        [0.3037],
        [0.3108]], grad_fn=<SigmoidBackward0>)
Parameter containing:
tensor([[-0.3923,  0.2766, -0.1637, -0.3870,  0.3878],
        [-0.0843, -0.0594,  0.0943,  0.0841, -0.2318],
        [ 0.1310,  0.0497,  0.0810,  0.4185,  0.1090]], requires_grad=True) Parameter containing:
tensor([-0.1061, -0.0570,  0.3857], requires_grad=True)
Parameter containing:
tensor([[ 0.3811, -0.0543, -0.4551]], requires_grad=True) Parameter containing:
tensor([-0.4964], requires_grad=True)


In [10]:
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [24]:
"""
5 Nodes in Input Layer --> 3 Nodes in Hidden Layer --> 1 node in output Layer
"""

import torch
import torch.nn as nn


class Model(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        # This is Sequential containter We have more like this
        self.network = nn.Sequential(
            nn.Linear(num_features, 30),
            nn.ReLU(),
            nn.Linear(30, 10),
            nn.ReLU(),
            nn.Linear(10, 3),
            nn.ReLU(),
            nn.Linear(3, 1),
            nn.Sigmoid(),
        )

    def forward(self, features):
        return self.network(features)

In [25]:
features = torch.rand(100, 50)
model = Model(features.shape[1])
# print(f"Model Output: {model(features)}")

for name, param in model.named_parameters():
    print(f"Name: {name} | Shape: {param.data.shape}")

Name: network.0.weight | Shape: torch.Size([30, 50])
Name: network.0.bias | Shape: torch.Size([30])
Name: network.2.weight | Shape: torch.Size([10, 30])
Name: network.2.bias | Shape: torch.Size([10])
Name: network.4.weight | Shape: torch.Size([3, 10])
Name: network.4.bias | Shape: torch.Size([3])
Name: network.6.weight | Shape: torch.Size([1, 3])
Name: network.6.bias | Shape: torch.Size([1])


In [27]:
summary(model, input_size=(10, 50))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 30]                  1,530
│    └─ReLU: 2-2                         [10, 30]                  --
│    └─Linear: 2-3                       [10, 10]                  310
│    └─ReLU: 2-4                         [10, 10]                  --
│    └─Linear: 2-5                       [10, 3]                   33
│    └─ReLU: 2-6                         [10, 3]                   --
│    └─Linear: 2-7                       [10, 1]                   4
│    └─Sigmoid: 2-8                      [10, 1]                   --
Total params: 1,877
Trainable params: 1,877
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.02
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.01
Estimated Total Size (MB): 0.01